### ISSUE TITLE
Missing "build-deps.sh"

### ISSUE THREAD

**Issue by Yogehi** [frida/frida-ci#1]
I'm trying to build a toolchain. Tried following the instructions at https://www.frida.re/docs/building/. I get the following error:

```
yogehi-linux@Yogehi-MSI:~/tmp$ ../frida-ci/create-toolchain-and-sdk.sh
Missing required script ../frida-ci/create-toolchain-and-sdk.sh/build-deps.sh
```

**Comment by oleavr** [comment]
That script shouldn't be used anymore. Please use `Makefile.toolchain.mk` in the `frida` repo.
